// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace GrpcService {
  public static partial class MsgService
  {
    static readonly string __ServiceName = "GrpcService.MsgService";

    static readonly grpc::Marshaller<global::GrpcService.GetMsgListRequest> __Marshaller_GetMsgListRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.GetMsgListRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.GetMsgListReply> __Marshaller_GetMsgListReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.GetMsgListReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.GetMsgOneRequest> __Marshaller_GetMsgOneRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.GetMsgOneRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.GetMsgOneReply> __Marshaller_GetMsgOneReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.GetMsgOneReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.EditMsgRequest> __Marshaller_EditMsgRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.EditMsgRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.EditMsgReply> __Marshaller_EditMsgReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.EditMsgReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.RemoveMsgRequest> __Marshaller_RemoveMsgRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.RemoveMsgRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.RemoveMsgReply> __Marshaller_RemoveMsgReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.RemoveMsgReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.HelloRequest> __Marshaller_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcService.HelloReply> __Marshaller_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcService.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcService.GetMsgListRequest, global::GrpcService.GetMsgListReply> __Method_GetList = new grpc::Method<global::GrpcService.GetMsgListRequest, global::GrpcService.GetMsgListReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetList",
        __Marshaller_GetMsgListRequest,
        __Marshaller_GetMsgListReply);

    static readonly grpc::Method<global::GrpcService.GetMsgOneRequest, global::GrpcService.GetMsgOneReply> __Method_GetOne = new grpc::Method<global::GrpcService.GetMsgOneRequest, global::GrpcService.GetMsgOneReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOne",
        __Marshaller_GetMsgOneRequest,
        __Marshaller_GetMsgOneReply);

    static readonly grpc::Method<global::GrpcService.EditMsgRequest, global::GrpcService.EditMsgReply> __Method_Edit = new grpc::Method<global::GrpcService.EditMsgRequest, global::GrpcService.EditMsgReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Edit",
        __Marshaller_EditMsgRequest,
        __Marshaller_EditMsgReply);

    static readonly grpc::Method<global::GrpcService.RemoveMsgRequest, global::GrpcService.RemoveMsgReply> __Method_Remove = new grpc::Method<global::GrpcService.RemoveMsgRequest, global::GrpcService.RemoveMsgReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Remove",
        __Marshaller_RemoveMsgRequest,
        __Marshaller_RemoveMsgReply);

    static readonly grpc::Method<global::GrpcService.HelloRequest, global::GrpcService.HelloReply> __Method_SayHello = new grpc::Method<global::GrpcService.HelloRequest, global::GrpcService.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_HelloRequest,
        __Marshaller_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcService.MsgReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MsgService</summary>
    public abstract partial class MsgServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcService.GetMsgListReply> GetList(global::GrpcService.GetMsgListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcService.GetMsgOneReply> GetOne(global::GrpcService.GetMsgOneRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcService.EditMsgReply> Edit(global::GrpcService.EditMsgRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcService.RemoveMsgReply> Remove(global::GrpcService.RemoveMsgRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcService.HelloReply> SayHello(global::GrpcService.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MsgService</summary>
    public partial class MsgServiceClient : grpc::ClientBase<MsgServiceClient>
    {
      /// <summary>Creates a new client for MsgService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MsgServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MsgService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MsgServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MsgServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MsgServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcService.GetMsgListReply GetList(global::GrpcService.GetMsgListRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcService.GetMsgListReply GetList(global::GrpcService.GetMsgListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.GetMsgListReply> GetListAsync(global::GrpcService.GetMsgListRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.GetMsgListReply> GetListAsync(global::GrpcService.GetMsgListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetList, null, options, request);
      }
      public virtual global::GrpcService.GetMsgOneReply GetOne(global::GrpcService.GetMsgOneRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOne(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcService.GetMsgOneReply GetOne(global::GrpcService.GetMsgOneRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOne, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.GetMsgOneReply> GetOneAsync(global::GrpcService.GetMsgOneRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOneAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.GetMsgOneReply> GetOneAsync(global::GrpcService.GetMsgOneRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOne, null, options, request);
      }
      public virtual global::GrpcService.EditMsgReply Edit(global::GrpcService.EditMsgRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Edit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcService.EditMsgReply Edit(global::GrpcService.EditMsgRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Edit, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.EditMsgReply> EditAsync(global::GrpcService.EditMsgRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return EditAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.EditMsgReply> EditAsync(global::GrpcService.EditMsgRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Edit, null, options, request);
      }
      public virtual global::GrpcService.RemoveMsgReply Remove(global::GrpcService.RemoveMsgRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Remove(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcService.RemoveMsgReply Remove(global::GrpcService.RemoveMsgRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Remove, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.RemoveMsgReply> RemoveAsync(global::GrpcService.RemoveMsgRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RemoveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.RemoveMsgReply> RemoveAsync(global::GrpcService.RemoveMsgRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Remove, null, options, request);
      }
      public virtual global::GrpcService.HelloReply SayHello(global::GrpcService.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcService.HelloReply SayHello(global::GrpcService.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.HelloReply> SayHelloAsync(global::GrpcService.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcService.HelloReply> SayHelloAsync(global::GrpcService.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MsgServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MsgServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MsgServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetList, serviceImpl.GetList)
          .AddMethod(__Method_GetOne, serviceImpl.GetOne)
          .AddMethod(__Method_Edit, serviceImpl.Edit)
          .AddMethod(__Method_Remove, serviceImpl.Remove)
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

  }
}
#endregion
